# JenkinsPodTemplate.yaml
#
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: worker
      image: alpine
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: 25m
          memory: 100Mi
